version: 2
updates:
  # Go modules updates (both security and minor updates)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"  # Check updates daily
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Security updates are prioritized
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-type: "development"
      - update-types: ["version-update:semver-major"]
    # Groups security updates into their own PRs
    groups:
      security-updates:
        applies-to: security-updates
        commit-message:
          prefix: "fix(security)"
          include: "scope"

  # GitHub Actions updates (both security and minor updates)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"  # Check updates daily
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    ignore:
      - update-types: ["version-update:semver-major"]
    # Groups security updates into separate PRs
    groups:
      security-updates:
        applies-to: security-updates
        commit-message:
          prefix: "fix(security)"
          include: "scope"
