version: 2
updates:
  # Security updates for Go modules (checked daily)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "fix(security)"
      include: "scope"
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-type: "development"

  # Regular updates for Go modules (checked weekly)
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      - update-types: ["version-update:semver-major"]

  # Security updates for GitHub Actions (checked daily)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "security"
    commit-message:
      prefix: "fix(security)"
      include: "scope"

  # Regular updates for GitHub Actions (checked weekly)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(actions)"
      include: "scope"
    ignore:
      - update-types: ["version-update:semver-major"]
