name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  integration:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Docker Compose
        run: docker compose version

      - name: Build and run integration tests
        run: |
          docker compose up --build --abort-on-container-exit --exit-code-from test-runner

      - name: Docker Compose Down
        if: always()
        run: docker compose down
